version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: gabeloh228
      MYSQL_DATABASE: supermarket
      MYSQL_USER: kirillberd
      MYSQL_PASSWORD: gabeloh228
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: